name: get-workflow-yaml
apiRevision: edurata.io/function/v1
description: Extracts YAML content from a cloned GitHub workflow file.

runtime: python3_10

packages:
  pip: "23.0"  # Ensure pip is updated
  setuptools: "65.5.0"  # Ensure setuptools is installed
  PyYAML: "6.0"  # Explicitly set PyYAML version
